version: '3.1'

services:
  hmbackend:
    image: hm-backend
    build: ./hm-backend
    networks:
      - hmnetwork
    ports:
      - "3000:3000"

  hmmongodb:
    image: mongo
    container_name: hotel-manager-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    networks:
      - hmnetwork
    

networks:
  hmnetwork: