version: '3.1'

services:
  hmbackend:
    image: hm-backend
    container_name: hotel-manager-backend
    build: ./hm-backend
    environment: 
      - MONGODB_USER=root
      - MONGODB_PASSWORD=example
      - MONGODB_HOST=hmmongodb

    networks:
      - hmbackend_net
    ports:
      - "3000:3000"

  hmmongodb:
    image: mongo
    container_name: hotel-manager-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
    networks:
      - hmbackend_net
    volumes:
      - hmmongodb_vol:/data/db
    # ports:
    #   - "27017:27017"

networks:
  hmbackend_net:

volumes:
  hmmongodb_vol:
